export default {
    captions: [
        {
            duration: 0,
            content: 'Oh',
            startOfParagraph: null,
            startTime: '00:00:45.838',
            endTime: '00:00:49.299',
        },
        {
            duration: 0,
            content: 'A newlywed couple just moved to town',
            startOfParagraph: null,
            startTime: '00:00:49.383',
            endTime: '00:00:52.427',
        },
        {
            duration: 0,
            content: 'A regular husband and wife',
            startOfParagraph: null,
            startTime: '00:00:52.845',
            endTime: '00:00:56.014',
        },
        {
            duration: 0,
            content: 'Who left the big city\nTo find a quiet life',
            startOfParagraph: null,
            startTime: '00:00:56.473',
            endTime: '00:01:01.562',
        },
        {
            duration: 0,
            content: 'WandaVision!',
            startOfParagraph: null,
            startTime: '00:01:02.062',
            endTime: '00:01:05.315',
        },
        {
            duration: 0,
            content: "She's a magical gal\nIn a small town locale",
            startOfParagraph: null,
            startTime: '00:01:08.610',
            endTime: '00:01:12.614',
        },
        {
            duration: 0,
            content: "He's a hubby who's part machine",
            startOfParagraph: null,
            startTime: '00:01:12.698',
            endTime: '00:01:16.285',
        },
        {
            duration: 0,
            content: 'How will this duo fit in and fulfill all?',
            startOfParagraph: null,
            startTime: '00:01:18.370',
            endTime: '00:01:21.623',
        },
        {
            duration: 0,
            content: "By sharing a love like you've never seen",
            startOfParagraph: null,
            startTime: '00:01:21.707',
            endTime: '00:01:26.920',
        },
        {
            duration: 0,
            content: 'WandaVision!',
            startOfParagraph: null,
            startTime: '00:01:28.714',
            endTime: '00:01:34.386',
        },
        {
            duration: 0,
            content: 'My wife and her flying saucers.',
            startOfParagraph: null,
            startTime: '00:01:49.109',
            endTime: '00:01:51.361',
        },
        {
            duration: 0,
            content: 'My husband and his indestructible head.',
            startOfParagraph: null,
            startTime: '00:01:51.445',
            endTime: '00:01:54.948',
        },
        {
            duration: 0,
            content: "Aren't we a fine pair?",
            startOfParagraph: null,
            startTime: '00:01:55.532',
            endTime: '00:01:57.034',
        },
        {
            duration: 0,
            content:
                'What do you say to silver dollar pancakes,\ncrispy hash browns, bacon, eggs,',
            startOfParagraph: null,
            startTime: '00:01:59.244',
            endTime: '00:02:04.124',
        },
        {
            duration: 0,
            content: 'freshly squeezed orange juice,\nand black coffee?',
            startOfParagraph: null,
            startTime: '00:02:04.208',
            endTime: '00:02:06.376',
        },
        {
            duration: 0,
            content: 'I say, "Oh, I don\'t eat food."',
            startOfParagraph: null,
            startTime: '00:02:06.460',
            endTime: '00:02:08.545',
        },
        {
            duration: 0,
            content: 'Well, that explains\nthe empty refrigerator.',
            startOfParagraph: null,
            startTime: '00:02:09.505',
            endTime: '00:02:11.882',
        },
        {
            duration: 0,
            content: '- Wanda?\n- Hmm?',
            startOfParagraph: null,
            startTime: '00:02:14.343',
            endTime: '00:02:15.385',
        },
        {
            duration: 0,
            content: 'Is there something special about today?',
            startOfParagraph: null,
            startTime: '00:02:15.886',
            endTime: '00:02:18.055',
        },
        {
            duration: 0,
            content: 'Well, I know the apron\nis a bit much, dear,',
            startOfParagraph: null,
            startTime: '00:02:18.472',
            endTime: '00:02:20.641',
        },
        {
            duration: 0,
            content: 'but I am doing my best to blend in.',
            startOfParagraph: null,
            startTime: '00:02:20.724',
            endTime: '00:02:22.976',
        },
        {
            duration: 0,
            content: 'No, no, there on the calendar.',
            startOfParagraph: null,
            startTime: '00:02:23.060',
            endTime: '00:02:24.394',
        },
        {
            duration: 0,
            content:
                "Someone's drawn a little heart\nright above today's date.",
            startOfParagraph: null,
            startTime: '00:02:24.478',
            endTime: '00:02:28.065',
        },
        {
            duration: 0,
            content: '- Oh, yes, the heart.\n- Hmm...',
            startOfParagraph: null,
            startTime: '00:02:29.316',
            endTime: '00:02:31.068',
        },
        {
            duration: 0,
            content: "Well, don't tell me\nyou have forgotten, Vis.",
            startOfParagraph: null,
            startTime: '00:02:32.277',
            endTime: '00:02:34.279',
        },
        {
            duration: 0,
            content: '"Forgotten"?',
            startOfParagraph: null,
            startTime: '00:02:34.404',
            endTime: '00:02:35.405',
        },
        {
            duration: 0,
            content:
                "Oh, Wanda, I'm incapable of forgetfulness.\nI remember everything.",
            startOfParagraph: null,
            startTime: '00:02:35.489',
            endTime: '00:02:37.991',
        },
        {
            duration: 0,
            content:
                "That's not an exaggeration.\nIn fact, I'm incapable of exaggeration.",
            startOfParagraph: null,
            startTime: '00:02:38.075',
            endTime: '00:02:41.662',
        },
        {
            duration: 0,
            content:
                "Well, then tell me what's so important\nabout today's date.",
            startOfParagraph: null,
            startTime: '00:02:41.745',
            endTime: '00:02:44.706',
        },
        {
            duration: 0,
            content: 'What was the question again?',
            startOfParagraph: null,
            startTime: '00:02:46.833',
            endTime: '00:02:48.043',
        },
        {
            duration: 0,
            content: "Oh, well,\nperhaps, you've forgotten yourself.",
            startOfParagraph: null,
            startTime: '00:02:48.585',
            endTime: '00:02:50.337',
        },
        {
            duration: 0,
            content: "Me? Heavens, no.\nI've been so looking forward to it.",
            startOfParagraph: null,
            startTime: '00:02:50.420',
            endTime: '00:02:53.215',
        },
        {
            duration: 0,
            content: 'As have I.',
            startOfParagraph: null,
            startTime: '00:02:53.298',
            endTime: '00:02:54.716',
        },
        {
            duration: 0,
            content: 'Today, we are celebrating...',
            startOfParagraph: null,
            startTime: '00:02:54.800',
            endTime: '00:02:56.468',
        },
        {
            duration: 0,
            content: 'You bet we are.',
            startOfParagraph: null,
            startTime: '00:02:57.052',
            endTime: '00:02:58.387',
        },
        {
            duration: 0,
            content: "- It's the first time we...\n- Mmm-hmm.",
            startOfParagraph: null,
            startTime: '00:02:58.470',
            endTime: '00:03:01.723',
        },
        {
            duration: 0,
            content: '...have ever celebrated\nthis occasion before.',
            startOfParagraph: null,
            startTime: '00:03:01.807',
            endTime: '00:03:04.560',
        },
        {
            duration: 0,
            content: "It's a special day!",
            startOfParagraph: null,
            startTime: '00:03:04.643',
            endTime: '00:03:06.228',
        },
        {
            duration: 0,
            content: '- Perhaps an evening...\n- Of great significance...',
            startOfParagraph: null,
            startTime: '00:03:06.311',
            endTime: '00:03:08.355',
        },
        {
            duration: 0,
            content: '- To us both!\n- Naturally.',
            startOfParagraph: null,
            startTime: '00:03:08.438',
            endTime: '00:03:09.523',
        },
        {
            duration: 0,
            content: '- Obviously.\n- Exactly.',
            startOfParagraph: null,
            startTime: '00:03:09.606',
            endTime: '00:03:11.066',
        },
        {
            duration: 0,
            content: 'Well done, us.',
            startOfParagraph: null,
            startTime: '00:03:11.984',
            endTime: '00:03:12.985',
        },
        {
            duration: 0,
            content: 'All right.',
            startOfParagraph: null,
            startTime: '00:03:13.527',
            endTime: '00:03:14.903',
        },
        {
            duration: 0,
            content: "Well, that's me off to work, then.",
            startOfParagraph: null,
            startTime: '00:03:15.404',
            endTime: '00:03:17.364',
        },
        {
            duration: 0,
            content: "Oh, don't forget!",
            startOfParagraph: null,
            startTime: '00:03:18.115',
            endTime: '00:03:19.116',
        },
        {
            duration: 0,
            content: "I haven't.",
            startOfParagraph: null,
            startTime: '00:03:20.033',
            endTime: '00:03:21.159',
        },
        {
            duration: 0,
            content: 'Oh!',
            startOfParagraph: null,
            startTime: '00:03:22.202',
            endTime: '00:03:23.245',
        },
        {
            duration: 0,
            content: 'Have a good day, dear!',
            startOfParagraph: null,
            startTime: '00:03:29.126',
            endTime: '00:03:30.127',
        },
        {
            duration: 0,
            content: 'Oh!',
            startOfParagraph: null,
            startTime: '00:03:52.024',
            endTime: '00:03:53.025',
        },
        {
            duration: 0,
            content: "Hello, dear.\nI'm Agnes, your neighbor to the right.",
            startOfParagraph: null,
            startTime: '00:03:53.108',
            endTime: '00:03:55.861',
        },
        {
            duration: 0,
            content: 'My right, not yours.',
            startOfParagraph: null,
            startTime: '00:03:55.986',
            endTime: '00:03:57.487',
        },
        {
            duration: 0,
            content:
                'Forgive me for not stopping by sooner\nto welcome you to the block.',
            startOfParagraph: null,
            startTime: '00:03:57.571',
            endTime: '00:04:00.490',
        },
        {
            duration: 0,
            content: "My mother-in-law was in town, so I wasn't.",
            startOfParagraph: null,
            startTime: '00:04:00.574',
            endTime: '00:04:03.118',
        },
        {
            duration: 0,
            content: "So, what's your name? Where are you from?",
            startOfParagraph: null,
            startTime: '00:04:04.661',
            endTime: '00:04:06.830',
        },
        {
            duration: 0,
            content: "And most importantly,\nhow's your bridge game, hon?",
            startOfParagraph: null,
            startTime: '00:04:06.914',
            endTime: '00:04:09.458',
        },
        {
            duration: 0,
            content: "I'm Wanda.",
            startOfParagraph: null,
            startTime: '00:04:11.376',
            endTime: '00:04:12.377',
        },
        {
            duration: 0,
            content: 'Wanda. Charmed.',
            startOfParagraph: null,
            startTime: '00:04:12.794',
            endTime: '00:04:15.130',
        },
        {
            duration: 0,
            content: 'Golly, you settled in fast!',
            startOfParagraph: null,
            startTime: '00:04:16.215',
            endTime: '00:04:18.717',
        },
        {
            duration: 0,
            content: 'Did you use a moving company?',
            startOfParagraph: null,
            startTime: '00:04:18.800',
            endTime: '00:04:20.344',
        },
        {
            duration: 0,
            content: "I sure did.\nThose boxes don't move themselves.",
            startOfParagraph: null,
            startTime: '00:04:20.844',
            endTime: '00:04:24.348',
        },
        {
            duration: 0,
            content:
                "So what's a single gal like you doing\nrattling around this big house?",
            startOfParagraph: null,
            startTime: '00:04:25.724',
            endTime: '00:04:29.853',
        },
        {
            duration: 0,
            content: "Oh, no, I'm not single.",
            startOfParagraph: null,
            startTime: '00:04:29.937',
            endTime: '00:04:31.188',
        },
        {
            duration: 0,
            content: "Oh, I don't see a ring.",
            startOfParagraph: null,
            startTime: '00:04:31.271',
            endTime: '00:04:32.731',
        },
        {
            duration: 0,
            content: "Well, I assure you I'm married.",
            startOfParagraph: null,
            startTime: '00:04:32.814',
            endTime: '00:04:35.150',
        },
        {
            duration: 0,
            content: 'To a man. A human one and tall.',
            startOfParagraph: null,
            startTime: '00:04:35.317',
            endTime: '00:04:37.694',
        },
        {
            duration: 0,
            content:
                "As a matter of fact, he'll be home\nlater tonight for a special occasion.",
            startOfParagraph: null,
            startTime: '00:04:37.778',
            endTime: '00:04:41.198',
        },
        {
            duration: 0,
            content: 'Just the two of us.',
            startOfParagraph: null,
            startTime: '00:04:41.281',
            endTime: '00:04:42.407',
        },
        {
            duration: 0,
            content: "Oh, is it somebody's birthday?",
            startOfParagraph: null,
            startTime: '00:04:42.491',
            endTime: '00:04:43.867',
        },
        {
            duration: 0,
            content: 'Not a birthday.',
            startOfParagraph: null,
            startTime: '00:04:43.951',
            endTime: '00:04:45.536',
        },
        {
            duration: 0,
            content: "Well, today isn't a holiday, is it?",
            startOfParagraph: null,
            startTime: '00:04:45.619',
            endTime: '00:04:47.287',
        },
        {
            duration: 0,
            content: "No, it's not a holiday.",
            startOfParagraph: null,
            startTime: '00:04:47.371',
            endTime: '00:04:49.706',
        },
        {
            duration: 0,
            content: 'An anniversary then?',
            startOfParagraph: null,
            startTime: '00:04:49.790',
            endTime: '00:04:51.208',
        },
        {
            duration: 0,
            content: 'Ye... Yes!',
            startOfParagraph: null,
            startTime: '00:04:51.291',
            endTime: '00:04:52.543',
        },
        {
            duration: 0,
            content: "Yes! It's our anniversary!",
            startOfParagraph: null,
            startTime: '00:04:52.626',
            endTime: '00:04:55.379',
        },
        {
            duration: 0,
            content: 'Oh, how marvelous!',
            startOfParagraph: null,
            startTime: '00:04:55.462',
            endTime: '00:04:57.965',
        },
        {
            duration: 0,
            content: 'How many years?',
            startOfParagraph: null,
            startTime: '00:04:58.048',
            endTime: '00:04:59.383',
        },
        {
            duration: 0,
            content: "Well, it feels like\nwe've always been together.",
            startOfParagraph: null,
            startTime: '00:04:59.967',
            endTime: '00:05:02.594',
        },
        {
            duration: 0,
            content: 'Lucky gal.',
            startOfParagraph: null,
            startTime: '00:05:02.678',
            endTime: '00:05:04.096',
        },
        {
            duration: 0,
            content: 'The only way\nRalph would remember our anniversary',
            startOfParagraph: null,
            startTime: '00:05:04.680',
            endTime: '00:05:07.057',
        },
        {
            duration: 0,
            content: 'is if there was a beer named June 2nd.',
            startOfParagraph: null,
            startTime: '00:05:07.140',
            endTime: '00:05:09.268',
        },
        {
            duration: 0,
            content: '- So, what do you have planned?\n- How do you mean?',
            startOfParagraph: null,
            startTime: '00:05:10.561',
            endTime: '00:05:13.063',
        },
        {
            duration: 0,
            content: 'For your special night.',
            startOfParagraph: null,
            startTime: '00:05:13.146',
            endTime: '00:05:14.690',
        },
        {
            duration: 0,
            content: "A young thing like you\ndoesn't have to do much,",
            startOfParagraph: null,
            startTime: '00:05:15.274',
            endTime: '00:05:17.651',
        },
        {
            duration: 0,
            content: "but it's still fun to set the scene.",
            startOfParagraph: null,
            startTime: '00:05:17.776',
            endTime: '00:05:20.028',
        },
        {
            duration: 0,
            content: 'Say, I was just reading\na crackerjack magazine article',
            startOfParagraph: null,
            startTime: '00:05:20.571',
            endTime: '00:05:24.783',
        },
        {
            duration: 0,
            content:
                'called "How To Treat Your Husband\nTo Keep Your Husband,"',
            startOfParagraph: null,
            startTime: '00:05:24.867',
            endTime: '00:05:28.912',
        },
        {
            duration: 0,
            content: 'and let me tell you,\nwhat Ralph could really use',
            startOfParagraph: null,
            startTime: '00:05:28.996',
            endTime: '00:05:31.582',
        },
        {
            duration: 0,
            content:
                'is, "How To Goose Your Wife\nSo You Don\'t Lose Your Wife."',
            startOfParagraph: null,
            startTime: '00:05:31.665',
            endTime: '00:05:35.419',
        },
        {
            duration: 0,
            content: "Hang on. I'll go grab it\nand we can start planning.",
            startOfParagraph: null,
            startTime: '00:05:36.962',
            endTime: '00:05:40.215',
        },
        {
            duration: 0,
            content: 'Oh, this is gonna be a gas!',
            startOfParagraph: null,
            startTime: '00:05:40.299',
            endTime: '00:05:42.634',
        },
        {
            duration: 0,
            content: 'Oh...',
            startOfParagraph: null,
            startTime: '00:05:45.596',
            endTime: '00:05:46.597',
        },
        {
            duration: 0,
            content: "Or you\ndon't go out Friday night Yakety yak!",
            startOfParagraph: null,
            startTime: '00:05:48.557',
            endTime: '00:05:52.186',
        },
        {
            duration: 0,
            content: 'You just put on your coat and hat',
            startOfParagraph: null,
            startTime: '00:05:52.811',
            endTime: '00:05:55.355',
        },
        {
            duration: 0,
            content:
                'Here are those computational forms\nthat you requested, Norm.',
            startOfParagraph: null,
            startTime: '00:05:56.231',
            endTime: '00:06:00.777',
        },
        {
            duration: 0,
            content: 'There you go.',
            startOfParagraph: null,
            startTime: '00:06:01.528',
            endTime: '00:06:02.529',
        },
        {
            duration: 0,
            content: 'Gee willikers, that was fast!',
            startOfParagraph: null,
            startTime: '00:06:03.780',
            endTime: '00:06:05.616',
        },
        {
            duration: 0,
            content: "Hey, the music\nisn't bothering you, is it, pal?",
            startOfParagraph: null,
            startTime: '00:06:06.658',
            endTime: '00:06:08.577',
        },
        {
            duration: 0,
            content: 'In terms of distraction from work,',
            startOfParagraph: null,
            startTime: '00:06:08.660',
            endTime: '00:06:10.204',
        },
        {
            duration: 0,
            content: 'or the largely nonsensical\nnature of the lyrics?',
            startOfParagraph: null,
            startTime: '00:06:10.287',
            endTime: '00:06:12.623',
        },
        {
            duration: 0,
            content: '- The first one.\n- Ah, no, thank you, Norm.',
            startOfParagraph: null,
            startTime: '00:06:13.832',
            endTime: '00:06:16.293',
        },
        {
            duration: 0,
            content: "Hey, is there somethin'\nI can help you with, buddy?",
            startOfParagraph: null,
            startTime: '00:06:17.586',
            endTime: '00:06:20.088',
        },
        {
            duration: 0,
            content: 'Yes, as a matter of fact, there is.',
            startOfParagraph: null,
            startTime: '00:06:20.964',
            endTime: '00:06:22.466',
        },
        {
            duration: 0,
            content:
                'Would you be so good as to tell me\nwhat it is we do here exactly?',
            startOfParagraph: null,
            startTime: '00:06:22.549',
            endTime: '00:06:27.721',
        },
        {
            duration: 0,
            content: 'Do we make something?',
            startOfParagraph: null,
            startTime: '00:06:28.472',
            endTime: '00:06:30.182',
        },
        {
            duration: 0,
            content: '- No.\n- Right.',
            startOfParagraph: null,
            startTime: '00:06:30.265',
            endTime: '00:06:31.558',
        },
        {
            duration: 0,
            content: 'Do we buy or sell something?',
            startOfParagraph: null,
            startTime: '00:06:31.642',
            endTime: '00:06:34.061',
        },
        {
            duration: 0,
            content: 'No and no.',
            startOfParagraph: null,
            startTime: '00:06:34.144',
            endTime: '00:06:35.354',
        },
        {
            duration: 0,
            content: 'Then what is the purpose of this company?',
            startOfParagraph: null,
            startTime: '00:06:35.437',
            endTime: '00:06:37.731',
        },
        {
            duration: 0,
            content:
                "All I know is, since you've gotten here,\nproductivity has gone up 300%.",
            startOfParagraph: null,
            startTime: '00:06:38.315',
            endTime: '00:06:42.402',
        },
        {
            duration: 0,
            content: "Yes, but what is it we're producing?",
            startOfParagraph: null,
            startTime: '00:06:42.528',
            endTime: '00:06:44.738',
        },
        {
            duration: 0,
            content: 'Computational forms.',
            startOfParagraph: null,
            startTime: '00:06:44.821',
            endTime: '00:06:46.198',
        },
        {
            duration: 0,
            content: 'And no one can process the data\nquite like you do, pal.',
            startOfParagraph: null,
            startTime: '00:06:46.281',
            endTime: '00:06:48.700',
        },
        {
            duration: 0,
            content: "You're like a walking computer.",
            startOfParagraph: null,
            startTime: '00:06:48.784',
            endTime: '00:06:50.494',
        },
        {
            duration: 0,
            content: 'What? I most certainly am not.',
            startOfParagraph: null,
            startTime: '00:06:50.577',
            endTime: '00:06:52.621',
        },
        {
            duration: 0,
            content:
                "I'm a regular carbon-based employee\nmade entirely of organic matter,",
            startOfParagraph: null,
            startTime: '00:06:52.704',
            endTime: '00:06:55.791',
        },
        {
            duration: 0,
            content: 'much like yourself, Norm.',
            startOfParagraph: null,
            startTime: '00:06:55.874',
            endTime: '00:06:57.834',
        },
        {
            duration: 0,
            content: "Hey! What's got your feathers all ruffled?",
            startOfParagraph: null,
            startTime: '00:06:57.918',
            endTime: '00:07:00.754',
        },
        {
            duration: 0,
            content: "Yes, I'm sorry, I'm a tad on edge.",
            startOfParagraph: null,
            startTime: '00:07:02.005',
            endTime: '00:07:03.841',
        },
        {
            duration: 0,
            content:
                "You see, it appears\nthere's something special about today,",
            startOfParagraph: null,
            startTime: '00:07:03.924',
            endTime: '00:07:06.927',
        },
        {
            duration: 0,
            content: "special to Wanda, that's my wife,",
            startOfParagraph: null,
            startTime: '00:07:07.010',
            endTime: '00:07:08.637',
        },
        {
            duration: 0,
            content:
                "and gee, I can't, for the life of me,\nrecall what it is.",
            startOfParagraph: null,
            startTime: '00:07:08.720',
            endTime: '00:07:12.683',
        },
        {
            duration: 0,
            content: 'Mmm... Oh!',
            startOfParagraph: null,
            startTime: '00:07:13.058',
            endTime: '00:07:14.643',
        },
        {
            duration: 0,
            content: 'Good to see you.',
            startOfParagraph: null,
            startTime: '00:07:16.812',
            endTime: '00:07:17.813',
        },
        {
            duration: 0,
            content: '- Vision.\n- Yes?',
            startOfParagraph: null,
            startTime: '00:07:18.397',
            endTime: '00:07:19.648',
        },
        {
            duration: 0,
            content: 'Wife and I\nare looking forward to this evening.',
            startOfParagraph: null,
            startTime: '00:07:19.731',
            endTime: '00:07:21.692',
        },
        {
            duration: 0,
            content: 'Mr. Hart. Of course!',
            startOfParagraph: null,
            startTime: '00:07:22.818',
            endTime: '00:07:24.778',
        },
        {
            duration: 0,
            content: 'Dinner with Mr. Hart\nand his dear lady wife, Mrs. Hart.',
            startOfParagraph: null,
            startTime: '00:07:25.320',
            endTime: '00:07:28.198',
        },
        {
            duration: 0,
            content: "That's what I said.\nWhat's wrong with you?",
            startOfParagraph: null,
            startTime: '00:07:28.282',
            endTime: '00:07:30.033',
        },
        {
            duration: 0,
            content:
                '- Have you got a screw loose?\n- Oh, no, sir. Screws all tightened, sir.',
            startOfParagraph: null,
            startTime: '00:07:30.117',
            endTime: '00:07:33.412',
        },
        {
            duration: 0,
            content: 'Yes, I should hope so.',
            startOfParagraph: null,
            startTime: '00:07:33.495',
            endTime: '00:07:35.038',
        },
        {
            duration: 0,
            content: 'Employee dinners\nare a rite of passage',
            startOfParagraph: null,
            startTime: '00:07:35.581',
            endTime: '00:07:37.082',
        },
        {
            duration: 0,
            content: '- for the new hires.\n- Ah.',
            startOfParagraph: null,
            startTime: '00:07:37.165',
            endTime: '00:07:38.542',
        },
        {
            duration: 0,
            content: 'Jones over there failed miserably.',
            startOfParagraph: null,
            startTime: '00:07:38.625',
            endTime: '00:07:40.419',
        },
        {
            duration: 0,
            content: "Isn't that right, Jones?",
            startOfParagraph: null,
            startTime: '00:07:40.502',
            endTime: '00:07:41.753',
        },
        {
            duration: 0,
            content: 'The wife thought\nfive courses would be sufficient.',
            startOfParagraph: null,
            startTime: '00:07:42.129',
            endTime: '00:07:44.423',
        },
        {
            duration: 0,
            content: 'And there was that paltry excuse\nfor entertainment.',
            startOfParagraph: null,
            startTime: '00:07:45.257',
            endTime: '00:07:47.384',
        },
        {
            duration: 0,
            content: 'A string quartet?',
            startOfParagraph: null,
            startTime: '00:07:48.260',
            endTime: '00:07:49.469',
        },
        {
            duration: 0,
            content:
                'And then you had that embarrassing display\nof beatnik enthusiasm.',
            startOfParagraph: null,
            startTime: '00:07:49.553',
            endTime: '00:07:53.265',
        },
        {
            duration: 0,
            content: 'I wore a turtleneck.',
            startOfParagraph: null,
            startTime: '00:07:53.348',
            endTime: '00:07:54.725',
        },
        {
            duration: 0,
            content:
                'Yes. Best of luck out there\nin the unemployment line, Jones.',
            startOfParagraph: null,
            startTime: '00:07:56.226',
            endTime: '00:07:58.854',
        },
        {
            duration: 0,
            content:
                'You know, I owe my success\nto being a keen judge of character.',
            startOfParagraph: null,
            startTime: '00:07:59.897',
            endTime: '00:08:02.733',
        },
        {
            duration: 0,
            content: 'No skeletons in your closet, eh, Vision?',
            startOfParagraph: null,
            startTime: '00:08:03.233',
            endTime: '00:08:05.194',
        },
        {
            duration: 0,
            content: "I don't have a skeleton, sir.",
            startOfParagraph: null,
            startTime: '00:08:06.403',
            endTime: '00:08:08.113',
        },
        {
            duration: 0,
            content:
                'Glad to hear it.\nYour future in this company depends on it.',
            startOfParagraph: null,
            startTime: '00:08:08.739',
            endTime: '00:08:12.284',
        },
        {
            duration: 0,
            content: "And you don't have a song?",
            startOfParagraph: null,
            startTime: '00:08:19.541',
            endTime: '00:08:20.751',
        },
        {
            duration: 0,
            content: 'Nothing special you played\nat your wedding?',
            startOfParagraph: null,
            startTime: '00:08:20.834',
            endTime: '00:08:22.753',
        },
        {
            duration: 0,
            content: 'No, nothing special.',
            startOfParagraph: null,
            startTime: '00:08:22.836',
            endTime: '00:08:24.046',
        },
        {
            duration: 0,
            content: "I'll just loan you some records then.",
            startOfParagraph: null,
            startTime: '00:08:24.546',
            endTime: '00:08:26.256',
        },
        {
            duration: 0,
            content: "So, we've got music covered,\ndecor, wardrobe. Oh!",
            startOfParagraph: null,
            startTime: '00:08:27.007',
            endTime: '00:08:31.386',
        },
        {
            duration: 0,
            content: 'What about seduction techniques?',
            startOfParagraph: null,
            startTime: '00:08:31.970',
            endTime: '00:08:33.805',
        },
        {
            duration: 0,
            content: 'Oh, I have those.',
            startOfParagraph: null,
            startTime: '00:08:34.556',
            endTime: '00:08:35.849',
        },
        {
            duration: 0,
            content: 'Of course, you do.',
            startOfParagraph: null,
            startTime: '00:08:35.933',
            endTime: '00:08:37.809',
        },
        {
            duration: 0,
            content: 'Just out of curiosity, what does it say?',
            startOfParagraph: null,
            startTime: '00:08:38.602',
            endTime: '00:08:40.979',
        },
        {
            duration: 0,
            content:
                'That you should stumble when\nyou walk into a room so he can catch you.',
            startOfParagraph: null,
            startTime: '00:08:41.563',
            endTime: '00:08:45.609',
        },
        {
            duration: 0,
            content: "It's romantic.",
            startOfParagraph: null,
            startTime: '00:08:46.026',
            endTime: '00:08:47.069',
        },
        {
            duration: 0,
            content: 'Any other tricks?',
            startOfParagraph: null,
            startTime: '00:08:47.152',
            endTime: '00:08:48.737',
        },
        {
            duration: 0,
            content:
                'You could point out that the death rate of\nsingle men is twice that of married men.',
            startOfParagraph: null,
            startTime: '00:08:48.820',
            endTime: '00:08:52.783',
        },
        {
            duration: 0,
            content: "Now, that's romantic.",
            startOfParagraph: null,
            startTime: '00:08:53.659',
            endTime: '00:08:55.536',
        },
        {
            duration: 0,
            content: 'Oh!',
            startOfParagraph: null,
            startTime: '00:08:57.663',
            endTime: '00:08:59.206',
        },
        {
            duration: 0,
            content: 'Vision residence.',
            startOfParagraph: null,
            startTime: '00:09:03.377',
            endTime: '00:09:04.378',
        },
        {
            duration: 0,
            content: '- Wanda, darling.\n- Vision, sweetheart.',
            startOfParagraph: null,
            startTime: '00:09:04.461',
            endTime: '00:09:06.505',
        },
        {
            duration: 0,
            content: 'Listen, about tonight...',
            startOfParagraph: null,
            startTime: '00:09:06.588',
            endTime: '00:09:07.673',
        },
        {
            duration: 0,
            content: "Don't worry, dear.\nI have everything under control.",
            startOfParagraph: null,
            startTime: '00:09:07.756',
            endTime: '00:09:11.134',
        },
        {
            duration: 0,
            content: 'Oh, well, that is a relief.',
            startOfParagraph: null,
            startTime: '00:09:11.218',
            endTime: '00:09:12.678',
        },
        {
            duration: 0,
            content: "I must confess, I'm really rather nervous.",
            startOfParagraph: null,
            startTime: '00:09:12.761',
            endTime: '00:09:15.264',
        },
        {
            duration: 0,
            content: '"Nervous"? Whatever for?',
            startOfParagraph: null,
            startTime: '00:09:15.848',
            endTime: '00:09:17.432',
        },
        {
            duration: 0,
            content:
                'Well, you know, darling,\nI still get a little tongue-tied.',
            startOfParagraph: null,
            startTime: '00:09:17.516',
            endTime: '00:09:20.018',
        },
        {
            duration: 0,
            content: 'Vis, after all this time...',
            startOfParagraph: null,
            startTime: '00:09:20.811',
            endTime: '00:09:24.690',
        },
        {
            duration: 0,
            content: "There's an awful lot\nriding on this one, Wanda.",
            startOfParagraph: null,
            startTime: '00:09:24.773',
            endTime: '00:09:26.775',
        },
        {
            duration: 0,
            content:
                "If tonight doesn't go just so,\nI think this could be the end.",
            startOfParagraph: null,
            startTime: '00:09:27.568',
            endTime: '00:09:31.655',
        },
        {
            duration: 0,
            content:
                "Well, it's just one night.\nThere's no need to get dramatic.",
            startOfParagraph: null,
            startTime: '00:09:33.073',
            endTime: '00:09:35.909',
        },
        {
            duration: 0,
            content:
                'Look, I think the best course of action\nis to impress the wife.',
            startOfParagraph: null,
            startTime: '00:09:35.993',
            endTime: '00:09:38.829',
        },
        {
            duration: 0,
            content:
                'And I think the best course of action\nis to impress the husband.',
            startOfParagraph: null,
            startTime: '00:09:38.912',
            endTime: '00:09:43.000',
        },
        {
            duration: 0,
            content: 'Well, wonderful!',
            startOfParagraph: null,
            startTime: '00:09:44.084',
            endTime: '00:09:45.127',
        },
        {
            duration: 0,
            content: "Glad to know we're both on the same page.",
            startOfParagraph: null,
            startTime: '00:09:45.210',
            endTime: '00:09:47.045',
        },
        {
            duration: 0,
            content: 'Until tonight, then, my, darling.',
            startOfParagraph: null,
            startTime: '00:09:47.129',
            endTime: '00:09:48.630',
        },
        {
            duration: 0,
            content: 'Until tonight.',
            startOfParagraph: null,
            startTime: '00:09:48.714',
            endTime: '00:09:49.923',
        },
        {
            duration: 0,
            content: 'Oh...',
            startOfParagraph: null,
            startTime: '00:09:50.591',
            endTime: '00:09:51.800',
        },
        {
            duration: 0,
            content: 'Is your husband tired of you\nburning his toast?',
            startOfParagraph: null,
            startTime: '00:09:57.681',
            endTime: '00:10:00.350',
        },
        {
            duration: 0,
            content: 'Try our new and improved ToastMate 2000.',
            startOfParagraph: null,
            startTime: '00:10:02.227',
            endTime: '00:10:04.646',
        },
        {
            duration: 0,
            content: "It's the go-to for clever housewives.",
            startOfParagraph: null,
            startTime: '00:10:05.189',
            endTime: '00:10:07.316',
        },
        {
            duration: 0,
            content: 'Say, this machine has some shine.',
            startOfParagraph: null,
            startTime: '00:10:07.649',
            endTime: '00:10:10.694',
        },
        {
            duration: 0,
            content: 'You said it.',
            startOfParagraph: null,
            startTime: '00:10:10.777',
            endTime: '00:10:11.904',
        },
        {
            duration: 0,
            content: 'Set the dial\nand get the taste back into your toast.',
            startOfParagraph: null,
            startTime: '00:10:11.987',
            endTime: '00:10:15.073',
        },
        {
            duration: 0,
            content: 'Top and bottom heating elements\ncan handle anything',
            startOfParagraph: null,
            startTime: '00:10:20.370',
            endTime: '00:10:23.290',
        },
        {
            duration: 0,
            content:
                'from meatloaf, to cherry pie,\nto open-faced cheese sandwiches.',
            startOfParagraph: null,
            startTime: '00:10:23.373',
            endTime: '00:10:27.544',
        },
        {
            duration: 0,
            content: 'The all new ToastMate 2000\nby Stark Industries.',
            startOfParagraph: null,
            startTime: '00:10:36.762',
            endTime: '00:10:40.516',
        },
        {
            duration: 0,
            content: 'Forget the past. This is your future.',
            startOfParagraph: null,
            startTime: '00:10:40.599',
            endTime: '00:10:43.519',
        },
        {
            duration: 0,
            content: 'Here we are!',
            startOfParagraph: null,
            startTime: '00:10:48.232',
            endTime: '00:10:49.441',
        },
        {
            duration: 0,
            content: 'Oh!',
            startOfParagraph: null,
            startTime: '00:10:50.859',
            endTime: '00:10:51.860',
        },
        {
            duration: 0,
            content: 'How very atmospheric!',
            startOfParagraph: null,
            startTime: '00:10:52.736',
            endTime: '00:10:54.947',
        },
        {
            duration: 0,
            content: "What's going on here, Vision?\nYou blow a fuse?",
            startOfParagraph: null,
            startTime: '00:10:55.030',
            endTime: '00:10:57.533',
        },
        {
            duration: 0,
            content:
                'Pardon me while I just go and fetch\nthe lady of the house.',
            startOfParagraph: null,
            startTime: '00:10:57.616',
            endTime: '00:11:01.328',
        },
        {
            duration: 0,
            content: 'Guess who?',
            startOfParagraph: null,
            startTime: '00:11:07.668',
            endTime: '00:11:08.752',
        },
        {
            duration: 0,
            content: 'Wanda!',
            startOfParagraph: null,
            startTime: '00:11:09.545',
            endTime: '00:11:10.546',
        },
        {
            duration: 0,
            content: 'Vision.',
            startOfParagraph: null,
            startTime: '00:11:11.171',
            endTime: '00:11:12.172',
        },
        {
            duration: 0,
            content: 'Oh! Oh!',
            startOfParagraph: null,
            startTime: '00:11:12.256',
            endTime: '00:11:13.590',
        },
        {
            duration: 0,
            content: 'Ah...',
            startOfParagraph: null,
            startTime: '00:11:14.174',
            endTime: '00:11:15.217',
        },
        {
            duration: 0,
            content: 'What is the meaning of this?',
            startOfParagraph: null,
            startTime: '00:11:15.300',
            endTime: '00:11:16.635',
        },
        {
            duration: 0,
            content: 'Well, what is...',
            startOfParagraph: null,
            startTime: '00:11:16.718',
            endTime: '00:11:18.846',
        },
        {
            duration: 0,
            content: 'Yeah, what is the meaning of...',
            startOfParagraph: null,
            startTime: '00:11:18.929',
            endTime: '00:11:20.264',
        },
        {
            duration: 0,
            content: 'Oh, the meaning of it!',
            startOfParagraph: null,
            startTime: '00:11:20.347',
            endTime: '00:11:21.390',
        },
        {
            duration: 0,
            content:
                'You want to know the meaning of it\nand the meaning of it',
            startOfParagraph: null,
            startTime: '00:11:21.473',
            endTime: '00:11:23.809',
        },
        {
            duration: 0,
            content:
                'is that this is the traditional\nSokovian greeting of hospitality.',
            startOfParagraph: null,
            startTime: '00:11:23.892',
            endTime: '00:11:29.314',
        },
        {
            duration: 0,
            content: '- Guess who?\n- Is that my host behind me?',
            startOfParagraph: null,
            startTime: '00:11:29.982',
            endTime: '00:11:32.192',
        },
        {
            duration: 0,
            content: 'It certainly is.',
            startOfParagraph: null,
            startTime: '00:11:32.276',
            endTime: '00:11:33.402',
        },
        {
            duration: 0,
            content: '- Lovely to make your acquaintance.\n- Yes!',
            startOfParagraph: null,
            startTime: '00:11:33.485',
            endTime: '00:11:35.863',
        },
        {
            duration: 0,
            content: 'See, I forgot to tell you\nmy wife is from Europe.',
            startOfParagraph: null,
            startTime: '00:11:35.946',
            endTime: '00:11:38.365',
        },
        {
            duration: 0,
            content: 'Oh, how exotic!',
            startOfParagraph: null,
            startTime: '00:11:39.199',
            endTime: '00:11:41.243',
        },
        {
            duration: 0,
            content: "We don't break bread with Bolsheviks.",
            startOfParagraph: null,
            startTime: '00:11:41.326',
            endTime: '00:11:43.161',
        },
        {
            duration: 0,
            content: 'Oh, hush, Arthur!',
            startOfParagraph: null,
            startTime: '00:11:43.245',
            endTime: '00:11:44.663',
        },
        {
            duration: 0,
            content: 'Have you no culture at all?',
            startOfParagraph: null,
            startTime: '00:11:44.746',
            endTime: '00:11:47.291',
        },
        {
            duration: 0,
            content: 'And that dress!',
            startOfParagraph: null,
            startTime: '00:11:47.374',
            endTime: '00:11:48.500',
        },
        {
            duration: 0,
            content: "Yes! It's... It's so...\nSokovian, is what it is! Yes!",
            startOfParagraph: null,
            startTime: '00:11:48.584',
            endTime: '00:11:53.422',
        },
        {
            duration: 0,
            content:
                'Can I just see you in the kitchen\nfor a moment, sweetheart?',
            startOfParagraph: null,
            startTime: '00:11:53.922',
            endTime: '00:11:57.384',
        },
        {
            duration: 0,
            content: 'Oh, yes!',
            startOfParagraph: null,
            startTime: '00:11:57.467',
            endTime: '00:11:58.468',
        },
        {
            duration: 0,
            content: '- Who are those people?\n- What are you wearing?',
            startOfParagraph: null,
            startTime: '00:12:01.096',
            endTime: '00:12:02.973',
        },
        {
            duration: 0,
            content: '- Why are they here?\n- What are you wearing?',
            startOfParagraph: null,
            startTime: '00:12:03.056',
            endTime: '00:12:05.017',
        },
        {
            duration: 0,
            content: "Well, it's our anniversary!",
            startOfParagraph: null,
            startTime: '00:12:05.100',
            endTime: '00:12:06.435',
        },
        {
            duration: 0,
            content: 'Our anniversary of what?',
            startOfParagraph: null,
            startTime: '00:12:06.518',
            endTime: '00:12:07.769',
        },
        {
            duration: 0,
            content: "Well, if you don't know,\nI'm not going to tell you!",
            startOfParagraph: null,
            startTime: '00:12:07.853',
            endTime: '00:12:10.272',
        },
        {
            duration: 0,
            content: 'That... That man through there\nis my boss, Mr. Hart!',
            startOfParagraph: null,
            startTime: '00:12:11.231',
            endTime: '00:12:14.401',
        },
        {
            duration: 0,
            content: 'And his dear lady wife, Mrs. Hart!',
            startOfParagraph: null,
            startTime: '00:12:14.484',
            endTime: '00:12:16.236',
        },
        {
            duration: 0,
            content: 'The heart on the calendar\nwas an abbreviation!',
            startOfParagraph: null,
            startTime: '00:12:16.320',
            endTime: '00:12:19.072',
        },
        {
            duration: 0,
            content:
                'You move at the speed of sound and I can\nmake a pen float through the air.',
            startOfParagraph: null,
            startTime: '00:12:19.156',
            endTime: '00:12:22.326',
        },
        {
            duration: 0,
            content: 'Who needs to abbreviate?',
            startOfParagraph: null,
            startTime: '00:12:22.409',
            endTime: '00:12:23.827',
        },
        {
            duration: 0,
            content:
                "Darling, listen, it's all romantic\nto do the candles, the music,",
            startOfParagraph: null,
            startTime: '00:12:23.911',
            endTime: '00:12:26.955',
        },
        {
            duration: 0,
            content: '- that stunning outfit...\n- Well...',
            startOfParagraph: null,
            startTime: '00:12:27.039',
            endTime: '00:12:28.874',
        },
        {
            duration: 0,
            content: "I don't wanna be unappreciative,\nbut right now...",
            startOfParagraph: null,
            startTime: '00:12:28.957',
            endTime: '00:12:31.251',
        },
        {
            duration: 0,
            content:
                'Your boss and his wife\nare expecting a home-cooked meal.',
            startOfParagraph: null,
            startTime: '00:12:31.335',
            endTime: '00:12:33.754',
        },
        {
            duration: 0,
            content: 'Exactly.',
            startOfParagraph: null,
            startTime: '00:12:33.837',
            endTime: '00:12:34.838',
        },
        {
            duration: 0,
            content: "Any chance they'd settle",
            startOfParagraph: null,
            startTime: '00:12:35.923',
            endTime: '00:12:36.965',
        },
        {
            duration: 0,
            content:
                'for a single chocolate-covered strawberry\nsplit three ways?',
            startOfParagraph: null,
            startTime: '00:12:37.049',
            endTime: '00:12:39.676',
        },
        {
            duration: 0,
            content: 'Uh...',
            startOfParagraph: null,
            startTime: '00:12:39.760',
            endTime: '00:12:41.011',
        },
        {
            duration: 0,
            content: 'I might have a better idea.',
            startOfParagraph: null,
            startTime: '00:12:41.094',
            endTime: '00:12:42.596',
        },
        {
            duration: 0,
            content: 'Hmm.',
            startOfParagraph: null,
            startTime: '00:12:45.265',
            endTime: '00:12:46.308',
        },
        {
            duration: 0,
            content:
                'So I said, "If we orient the forms\nhorizontally rather than vertically,',
            startOfParagraph: null,
            startTime: '00:12:46.558',
            endTime: '00:12:50.312',
        },
        {
            duration: 0,
            content:
                '"we can use twice the paper,\nwe can bill twice the cost."',
            startOfParagraph: null,
            startTime: '00:12:50.896',
            endTime: '00:12:54.191',
        },
        {
            duration: 0,
            content: 'You truly are a pioneer!',
            startOfParagraph: null,
            startTime: '00:12:55.776',
            endTime: '00:12:57.653',
        },
        {
            duration: 0,
            content: 'But the larger purpose of the forms is...',
            startOfParagraph: null,
            startTime: '00:12:57.736',
            endTime: '00:13:00.364',
        },
        {
            duration: 0,
            content: 'Was to analyze our input and our output.',
            startOfParagraph: null,
            startTime: '00:13:00.489',
            endTime: '00:13:02.324',
        },
        {
            duration: 0,
            content: 'Huh.',
            startOfParagraph: null,
            startTime: '00:13:02.407',
            endTime: '00:13:03.408',
        },
        {
            duration: 0,
            content: "You're awfully dense, aren't you, Vision?",
            startOfParagraph: null,
            startTime: '00:13:04.451',
            endTime: '00:13:06.245',
        },
        {
            duration: 0,
            content: "Oh, Agnes! You're a life-saver!",
            startOfParagraph: null,
            startTime: '00:13:09.122',
            endTime: '00:13:10.707',
        },
        {
            duration: 0,
            content: 'What kind of housewife would I be',
            startOfParagraph: null,
            startTime: '00:13:10.791',
            endTime: '00:13:12.334',
        },
        {
            duration: 0,
            content:
                "if I didn't have a gourmet meal for four\njust lying about the place?",
            startOfParagraph: null,
            startTime: '00:13:12.417',
            endTime: '00:13:15.712',
        },
        {
            duration: 0,
            content: 'Well...',
            startOfParagraph: null,
            startTime: '00:13:15.796',
            endTime: '00:13:16.797',
        },
        {
            duration: 0,
            content:
                'Not that Ralph ever wants to eat\nanything but baked beans',
            startOfParagraph: null,
            startTime: '00:13:16.880',
            endTime: '00:13:19.424',
        },
        {
            duration: 0,
            content:
                'which explains a lot\nabout his personal appeal, mind you.',
            startOfParagraph: null,
            startTime: '00:13:19.508',
            endTime: '00:13:22.427',
        },
        {
            duration: 0,
            content: '- Oh, my!\n- Oh! Oh!',
            startOfParagraph: null,
            startTime: '00:13:22.845',
            endTime: '00:13:24.805',
        },
        {
            duration: 0,
            content: 'Do you think Wanda needs help\nin the kitchen?',
            startOfParagraph: null,
            startTime: '00:13:24.888',
            endTime: '00:13:26.849',
        },
        {
            duration: 0,
            content: "We haven't any tidbits\nor tartlets out here,",
            startOfParagraph: null,
            startTime: '00:13:26.932',
            endTime: '00:13:29.643',
        },
        {
            duration: 0,
            content: 'nary a pig in a blanket.',
            startOfParagraph: null,
            startTime: '00:13:29.726',
            endTime: '00:13:30.853',
        },
        {
            duration: 0,
            content: 'No, that...',
            startOfParagraph: null,
            startTime: '00:13:30.936',
            endTime: '00:13:32.145',
        },
        {
            duration: 0,
            content: "No, that's so kind of you, Mrs. Hart.",
            startOfParagraph: null,
            startTime: '00:13:32.521',
            endTime: '00:13:34.606',
        },
        {
            duration: 0,
            content: "But I'm sure\nshe's absolutely fine in there!",
            startOfParagraph: null,
            startTime: '00:13:34.690',
            endTime: '00:13:36.859',
        },
        {
            duration: 0,
            content:
                "Oh, thank you, Agnes.\nI think I've got it covered from here.",
            startOfParagraph: null,
            startTime: '00:13:36.942',
            endTime: '00:13:39.319',
        },
        {
            duration: 0,
            content: '- Oh, are you sure, dear?\n- Hmm.',
            startOfParagraph: null,
            startTime: '00:13:39.444',
            endTime: '00:13:40.571',
        },
        {
            duration: 0,
            content:
                'Many hands make light work.\nAnd many mouths make good gossip.',
            startOfParagraph: null,
            startTime: '00:13:40.654',
            endTime: '00:13:43.907',
        },
        {
            duration: 0,
            content: "You're so naughty!",
            startOfParagraph: null,
            startTime: '00:13:43.991',
            endTime: '00:13:45.409',
        },
        {
            duration: 0,
            content: 'Oh, shall I just pre-heat\nthe oven then, dear?',
            startOfParagraph: null,
            startTime: '00:13:45.492',
            endTime: '00:13:47.411',
        },
        {
            duration: 0,
            content: "- That won't be necessary.\n- Oh, All right, then.",
            startOfParagraph: null,
            startTime: '00:13:47.494',
            endTime: '00:13:49.830',
        },
        {
            duration: 0,
            content:
                "Well, I know you're in a pinch\nso this menu can be done in a snap.",
            startOfParagraph: null,
            startTime: '00:13:49.913',
            endTime: '00:13:52.833',
        },
        {
            duration: 0,
            content:
                'Lobster Thermidor with\nmini-minced meat turnovers to start.',
            startOfParagraph: null,
            startTime: '00:13:52.916',
            endTime: '00:13:55.627',
        },
        {
            duration: 0,
            content:
                'Chicken \u00e0 la King with twice-cooked\nnew potatoes for your second course,',
            startOfParagraph: null,
            startTime: '00:13:55.711',
            endTime: '00:13:58.755',
        },
        {
            duration: 0,
            content: 'and Steak Diane and mint jellies\nfor your main.',
            startOfParagraph: null,
            startTime: '00:13:58.839',
            endTime: '00:14:01.216',
        },
        {
            duration: 0,
            content: 'Do you set your own jellies, dear?',
            startOfParagraph: null,
            startTime: '00:14:01.925',
            endTime: '00:14:03.510',
        },
        {
            duration: 0,
            content: '- Yes.\n- Good girl.',
            startOfParagraph: null,
            startTime: '00:14:03.594',
            endTime: '00:14:05.596',
        },
        {
            duration: 0,
            content: 'Recipe cards are on the counter there.',
            startOfParagraph: null,
            startTime: '00:14:05.679',
            endTime: '00:14:07.681',
        },
        {
            duration: 0,
            content: 'Bon app\u00e9tit!',
            startOfParagraph: null,
            startTime: '00:14:07.764',
            endTime: '00:14:09.016',
        },
        {
            duration: 0,
            content: 'Oh!',
            startOfParagraph: null,
            startTime: '00:14:09.099',
            endTime: '00:14:10.517',
        },
        {
            duration: 0,
            content: 'Oh, oh.',
            startOfParagraph: null,
            startTime: '00:14:13.896',
            endTime: '00:14:15.022',
        },
        {
            duration: 0,
            content: 'You men stay put.',
            startOfParagraph: null,
            startTime: '00:14:15.105',
            endTime: '00:14:16.148',
        },
        {
            duration: 0,
            content:
                "- I sense a domestic emergency, so...\n- Mrs. Hart, please don't. You can't.",
            startOfParagraph: null,
            startTime: '00:14:16.231',
            endTime: '00:14:19.610',
        },
        {
            duration: 0,
            content: 'You... Please...',
            startOfParagraph: null,
            startTime: '00:14:19.693',
            endTime: '00:14:21.528',
        },
        {
            duration: 0,
            content: 'Yeah, take out the papers and the trash',
            startOfParagraph: null,
            startTime: '00:14:21.612',
            endTime: '00:14:25.657',
        },
        {
            duration: 0,
            content: "Or you won't get no spending cash",
            startOfParagraph: null,
            startTime: '00:14:25.741',
            endTime: '00:14:28.076',
        },
        {
            duration: 0,
            content: "If you don't scrub the kitchen floor",
            startOfParagraph: null,
            startTime: '00:14:29.494',
            endTime: '00:14:31.872',
        },
        {
            duration: 0,
            content: "You ain't gonna rock and roll no more",
            startOfParagraph: null,
            startTime: '00:14:33.081',
            endTime: '00:14:34.833',
        },
        {
            duration: 0,
            content: "Yakety yak!\nDon't talk back",
            startOfParagraph: null,
            startTime: '00:14:34.917',
            endTime: '00:14:36.793',
        },
        {
            duration: 0,
            content:
                "Well, why don't we have a nice\nsing-a-long, all together then, shall we?",
            startOfParagraph: null,
            startTime: '00:14:41.507',
            endTime: '00:14:45.511',
        },
        {
            duration: 0,
            content: 'Oh, no, too much!',
            startOfParagraph: null,
            startTime: '00:14:48.430',
            endTime: '00:14:50.057',
        },
        {
            duration: 0,
            content: 'Oh, no, not enough!',
            startOfParagraph: null,
            startTime: '00:14:53.143',
            endTime: '00:14:55.145',
        },
        {
            duration: 0,
            content: 'Old MacDonald had a farm',
            startOfParagraph: null,
            startTime: '00:14:56.021',
            endTime: '00:14:58.482',
        },
        {
            duration: 0,
            content: 'Ee-I-Ee-I-O',
            startOfParagraph: null,
            startTime: '00:14:58.565',
            endTime: '00:15:00.317',
        },
        {
            duration: 0,
            content: 'And on that farm he had a...',
            startOfParagraph: null,
            startTime: '00:15:00.400',
            endTime: '00:15:02.402',
        },
        {
            duration: 0,
            content: 'had a...',
            startOfParagraph: null,
            startTime: '00:15:04.821',
            endTime: '00:15:05.822',
        },
        {
            duration: 0,
            content: 'Pig.',
            startOfParagraph: null,
            startTime: '00:15:06.448',
            endTime: '00:15:07.449',
        },
        {
            duration: 0,
            content: 'Ee-I-Ee-I-O',
            startOfParagraph: null,
            startTime: '00:15:07.533',
            endTime: '00:15:09.076',
        },
        {
            duration: 0,
            content: '- With a...\n- Oink, oink...',
            startOfParagraph: null,
            startTime: '00:15:09.159',
            endTime: '00:15:10.160',
        },
        {
            duration: 0,
            content: '- Here and a...\n- Oink, oink...',
            startOfParagraph: null,
            startTime: '00:15:10.244',
            endTime: '00:15:11.286',
        },
        {
            duration: 0,
            content: '- There\n- Here an oink, there an oink',
            startOfParagraph: null,
            startTime: '00:15:11.370',
            endTime: '00:15:12.955',
        },
        {
            duration: 0,
            content: 'Everywhere an oink, oink',
            startOfParagraph: null,
            startTime: '00:15:13.038',
            endTime: '00:15:14.122',
        },
        {
            duration: 0,
            content: 'Old MacDonald had a farm',
            startOfParagraph: null,
            startTime: '00:15:14.206',
            endTime: '00:15:16.333',
        },
        {
            duration: 0,
            content: 'Ee-I-Ee-I-O',
            startOfParagraph: null,
            startTime: '00:15:16.416',
            endTime: '00:15:17.918',
        },
        {
            duration: 0,
            content:
                'Oh, what was I supposed to do next?\nOh, what was the main course again?',
            startOfParagraph: null,
            startTime: '00:15:18.001',
            endTime: '00:15:20.671',
        },
        {
            duration: 0,
            content: 'It was... Steak...',
            startOfParagraph: null,
            startTime: '00:15:20.754',
            endTime: '00:15:22.297',
        },
        {
            duration: 0,
            content: 'No. Steak...',
            startOfParagraph: null,
            startTime: '00:15:22.381',
            endTime: '00:15:23.757',
        },
        {
            duration: 0,
            content: 'Steak... Diane!',
            startOfParagraph: null,
            startTime: '00:15:23.841',
            endTime: '00:15:25.592',
        },
        {
            duration: 0,
            content: 'Yes?',
            startOfParagraph: null,
            startTime: '00:15:25.676',
            endTime: '00:15:26.718',
        },
        {
            duration: 0,
            content: 'Oh, I think that must be\nmy wife summoning me.',
            startOfParagraph: null,
            startTime: '00:15:27.803',
            endTime: '00:15:30.138',
        },
        {
            duration: 0,
            content: 'She calls you "Diane?"',
            startOfParagraph: null,
            startTime: '00:15:30.681',
            endTime: '00:15:32.307',
        },
        {
            duration: 0,
            content: "Yes, it's her pet name for me.",
            startOfParagraph: null,
            startTime: '00:15:33.308',
            endTime: '00:15:36.061',
        },
        {
            duration: 0,
            content: "I'm just coming, Fred.",
            startOfParagraph: null,
            startTime: '00:15:37.396',
            endTime: '00:15:40.232',
        },
        {
            duration: 0,
            content: 'Excuse me a moment.',
            startOfParagraph: null,
            startTime: '00:15:42.067',
            endTime: '00:15:43.193',
        },
        {
            duration: 0,
            content: 'Oh, no.',
            startOfParagraph: null,
            startTime: '00:15:47.072',
            endTime: '00:15:48.240',
        },
        {
            duration: 0,
            content: 'How can I be of assistance?',
            startOfParagraph: null,
            startTime: '00:15:49.867',
            endTime: '00:15:51.326',
        },
        {
            duration: 0,
            content:
                'Well, the chicken is no longer a chicken\nand the lobsters just flew the coop',
            startOfParagraph: null,
            startTime: '00:15:51.410',
            endTime: '00:15:54.913',
        },
        {
            duration: 0,
            content: 'so the steak is the last man standing.',
            startOfParagraph: null,
            startTime: '00:15:54.997',
            endTime: '00:15:56.623',
        },
        {
            duration: 0,
            content:
                'It says here I can cut down the prep time\nwith a meat tenderizer.',
            startOfParagraph: null,
            startTime: '00:15:57.124',
            endTime: '00:16:00.294',
        },
        {
            duration: 0,
            content: "Excellent plan. Where's the tenderizer?",
            startOfParagraph: null,
            startTime: '00:16:00.377',
            endTime: '00:16:02.546',
        },
        {
            duration: 0,
            content: "- I'm looking at him.\n- Ah.",
            startOfParagraph: null,
            startTime: '00:16:02.629',
            endTime: '00:16:04.339',
        },
        {
            duration: 0,
            content: 'Hoo-hoo in there!',
            startOfParagraph: null,
            startTime: '00:16:04.423',
            endTime: '00:16:05.465',
        },
        {
            duration: 0,
            content: 'Hoo-hoo back to you!',
            startOfParagraph: null,
            startTime: '00:16:05.549',
            endTime: '00:16:07.342',
        },
        {
            duration: 0,
            content: 'Okay.',
            startOfParagraph: null,
            startTime: '00:16:07.843',
            endTime: '00:16:08.844',
        },
        {
            duration: 0,
            content: "Finish the meat, find the lobsters.\nI'll be right back.",
            startOfParagraph: null,
            startTime: '00:16:08.927',
            endTime: '00:16:12.639',
        },
        {
            duration: 0,
            content: "I hope you're hungry.",
            startOfParagraph: null,
            startTime: '00:16:14.224',
            endTime: '00:16:15.559',
        },
        {
            duration: 0,
            content: 'Starved, is more like it.',
            startOfParagraph: null,
            startTime: '00:16:15.642',
            endTime: '00:16:16.894',
        },
        {
            duration: 0,
            content: 'My head is starting to feel woozy.',
            startOfParagraph: null,
            startTime: '00:16:16.977',
            endTime: '00:16:19.396',
        },
        {
            duration: 0,
            content: 'Were either of you aware',
            startOfParagraph: null,
            startTime: '00:16:22.107',
            endTime: '00:16:23.442',
        },
        {
            duration: 0,
            content:
                'that married men are killing single men\nat an alarming rate?',
            startOfParagraph: null,
            startTime: '00:16:23.525',
            endTime: '00:16:26.862',
        },
        {
            duration: 0,
            content: 'What are you going on about?',
            startOfParagraph: null,
            startTime: '00:16:27.529',
            endTime: '00:16:29.615',
        },
        {
            duration: 0,
            content: "And what's going on in there?",
            startOfParagraph: null,
            startTime: '00:16:29.698',
            endTime: '00:16:30.908',
        },
        {
            duration: 0,
            content: 'Whoo-hoo! Ho-ho!',
            startOfParagraph: null,
            startTime: '00:16:30.991',
            endTime: '00:16:33.535',
        },
        {
            duration: 0,
            content: 'Who could that be?',
            startOfParagraph: null,
            startTime: '00:16:36.330',
            endTime: '00:16:37.372',
        },
        {
            duration: 0,
            content: 'Coming!',
            startOfParagraph: null,
            startTime: '00:16:37.956',
            endTime: '00:16:39.208',
        },
        {
            duration: 0,
            content: "Oh, you didn't answer the back door.",
            startOfParagraph: null,
            startTime: '00:16:40.334',
            endTime: '00:16:42.211',
        },
        {
            duration: 0,
            content: 'For your upside-down cake.',
            startOfParagraph: null,
            startTime: '00:16:42.294',
            endTime: '00:16:43.921',
        },
        {
            duration: 0,
            content: 'Oh! Hi, I...',
            startOfParagraph: null,
            startTime: '00:16:44.004',
            endTime: '00:16:45.923',
        },
        {
            duration: 0,
            content: 'Who was that?',
            startOfParagraph: null,
            startTime: '00:16:46.006',
            endTime: '00:16:47.007',
        },
        {
            duration: 0,
            content: '- A salesman!\n- Telegram!',
            startOfParagraph: null,
            startTime: '00:16:47.090',
            endTime: '00:16:48.592',
        },
        {
            duration: 0,
            content: 'A man selling telegrams.',
            startOfParagraph: null,
            startTime: '00:16:48.675',
            endTime: '00:16:50.469',
        },
        {
            duration: 0,
            content: "Wouldn't you know it.\nGood news is more expensive.",
            startOfParagraph: null,
            startTime: '00:16:50.552',
            endTime: '00:16:52.638',
        },
        {
            duration: 0,
            content:
                "I couldn't find the lobsters and did you\nwant the meat tender or pulverized?",
            startOfParagraph: null,
            startTime: '00:16:53.514',
            endTime: '00:16:56.683',
        },
        {
            duration: 0,
            content: 'Oh, dear.',
            startOfParagraph: null,
            startTime: '00:16:56.767',
            endTime: '00:16:57.935',
        },
        {
            duration: 0,
            content: "Well. I think tonight's going swimmingly.",
            startOfParagraph: null,
            startTime: '00:16:59.603',
            endTime: '00:17:02.606',
        },
        {
            duration: 0,
            content: 'Anyone for Parcheesi?',
            startOfParagraph: null,
            startTime: '00:17:03.315',
            endTime: '00:17:05.526',
        },
        {
            duration: 0,
            content: '- My head is spinning.\n- Oh, Mrs. Hart...',
            startOfParagraph: null,
            startTime: '00:17:05.651',
            endTime: '00:17:08.570',
        },
        {
            duration: 0,
            content: "Did you hear that?\nMy wife's head is spinning.",
            startOfParagraph: null,
            startTime: '00:17:09.112',
            endTime: '00:17:11.031',
        },
        {
            duration: 0,
            content: "Generally speaking,\nI don't like her head to do that.",
            startOfParagraph: null,
            startTime: '00:17:11.114',
            endTime: '00:17:13.325',
        },
        {
            duration: 0,
            content: 'Time to improvise.',
            startOfParagraph: null,
            startTime: '00:17:15.577',
            endTime: '00:17:16.745',
        },
        {
            duration: 0,
            content:
                "You know, I'm beginning to think\nyou're not management material, Vision.",
            startOfParagraph: null,
            startTime: '00:17:18.288',
            endTime: '00:17:21.416',
        },
        {
            duration: 0,
            content: 'You know, I had high hopes for you.',
            startOfParagraph: null,
            startTime: '00:17:21.500',
            endTime: '00:17:23.126',
        },
        {
            duration: 0,
            content:
                "But from what I've seen here tonight,\nyou can barely keep it together.",
            startOfParagraph: null,
            startTime: '00:17:23.210',
            endTime: '00:17:26.839',
        },
        {
            duration: 0,
            content:
                "I mean, look around. There's all this\nchaos going on in your household.",
            startOfParagraph: null,
            startTime: '00:17:26.922',
            endTime: '00:17:29.925',
        },
        {
            duration: 0,
            content: 'Now, when are we gonna eat?',
            startOfParagraph: null,
            startTime: '00:17:31.176',
            endTime: '00:17:32.386',
        },
        {
            duration: 0,
            content: 'Dinner is served.',
            startOfParagraph: null,
            startTime: '00:17:32.469',
            endTime: '00:17:34.054',
        },
        {
            duration: 0,
            content: 'Ah!',
            startOfParagraph: null,
            startTime: '00:17:35.430',
            endTime: '00:17:36.431',
        },
        {
            duration: 0,
            content: 'Breakfast for dinner?',
            startOfParagraph: null,
            startTime: '00:17:37.683',
            endTime: '00:17:39.268',
        },
        {
            duration: 0,
            content: 'How very...',
            startOfParagraph: null,
            startTime: '00:17:40.769',
            endTime: '00:17:41.770',
        },
        {
            duration: 0,
            content: 'European.',
            startOfParagraph: null,
            startTime: '00:17:41.854',
            endTime: '00:17:43.188',
        },
        {
            duration: 0,
            content: "Ooh! Let's have a toast!",
            startOfParagraph: null,
            startTime: '00:17:44.273',
            endTime: '00:17:46.525',
        },
        {
            duration: 0,
            content: 'To my lovely and talented wife.',
            startOfParagraph: null,
            startTime: '00:17:47.317',
            endTime: '00:17:50.487',
        },
        {
            duration: 0,
            content: 'To our esteemed guests.',
            startOfParagraph: null,
            startTime: '00:17:50.612',
            endTime: '00:17:52.865',
        },
        {
            duration: 0,
            content: 'Yes. Cin cin.',
            startOfParagraph: null,
            startTime: '00:17:52.948',
            endTime: '00:17:54.324',
        },
        {
            duration: 0,
            content: 'Cheers.',
            startOfParagraph: null,
            startTime: '00:17:54.408',
            endTime: '00:17:55.409',
        },
        {
            duration: 0,
            content: 'Well, please eat before it gets cold.',
            startOfParagraph: null,
            startTime: '00:17:57.786',
            endTime: '00:17:59.538',
        },
        {
            duration: 0,
            content: '- Hmm?\n- Oh, Mrs. Hart, allow me.',
            startOfParagraph: null,
            startTime: '00:17:59.621',
            endTime: '00:18:01.498',
        },
        {
            duration: 0,
            content: 'So, where did you two move from?',
            startOfParagraph: null,
            startTime: '00:18:03.041',
            endTime: '00:18:05.419',
        },
        {
            duration: 0,
            content: 'What brought you here?',
            startOfParagraph: null,
            startTime: '00:18:06.044',
            endTime: '00:18:07.129',
        },
        {
            duration: 0,
            content:
                "How long have you been married?\nAnd why don't you have children yet?",
            startOfParagraph: null,
            startTime: '00:18:07.212',
            endTime: '00:18:10.507',
        },
        {
            duration: 0,
            content:
                'I think what my wife means to say\nis that we moved from...',
            startOfParagraph: null,
            startTime: '00:18:14.469',
            endTime: '00:18:19.725',
        },
        {
            duration: 0,
            content: 'Yes, we moved from...',
            startOfParagraph: null,
            startTime: '00:18:19.808',
            endTime: '00:18:21.518',
        },
        {
            duration: 0,
            content: 'And we were married...',
            startOfParagraph: null,
            startTime: '00:18:22.936',
            endTime: '00:18:24.438',
        },
        {
            duration: 0,
            content: 'Yes, yes, we were married in...',
            startOfParagraph: null,
            startTime: '00:18:24.521',
            endTime: '00:18:27.232',
        },
        {
            duration: 0,
            content: 'Well? Moved from where? Married when?',
            startOfParagraph: null,
            startTime: '00:18:27.941',
            endTime: '00:18:31.361',
        },
        {
            duration: 0,
            content: 'Now, patience, Arthur.',
            startOfParagraph: null,
            startTime: '00:18:31.486',
            endTime: '00:18:32.487',
        },
        {
            duration: 0,
            content: "They're setting up their story.\nLet them tell it.",
            startOfParagraph: null,
            startTime: '00:18:32.571',
            endTime: '00:18:34.781',
        },
        {
            duration: 0,
            content: 'We...',
            startOfParagraph: null,
            startTime: '00:18:35.240',
            endTime: '00:18:36.366',
        },
        {
            duration: 0,
            content: 'Our story...',
            startOfParagraph: null,
            startTime: '00:18:36.450',
            endTime: '00:18:38.243',
        },
        {
            duration: 0,
            content: 'Yes, what exactly is your story?',
            startOfParagraph: null,
            startTime: '00:18:39.494',
            endTime: '00:18:41.580',
        },
        {
            duration: 0,
            content: 'Oh, just leave the poor kids alone.',
            startOfParagraph: null,
            startTime: '00:18:41.663',
            endTime: '00:18:43.540',
        },
        {
            duration: 0,
            content:
                "No, really, I mean,\nI think it's a perfectly simple question.",
            startOfParagraph: null,
            startTime: '00:18:44.499',
            endTime: '00:18:47.044',
        },
        {
            duration: 0,
            content: 'Honestly.',
            startOfParagraph: null,
            startTime: '00:18:47.794',
            endTime: '00:18:48.962',
        },
        {
            duration: 0,
            content: 'Why did you come here?',
            startOfParagraph: null,
            startTime: '00:18:49.046',
            endTime: '00:18:50.255',
        },
        {
            duration: 0,
            content: 'Why?',
            startOfParagraph: null,
            startTime: '00:18:51.757',
            endTime: '00:18:52.966',
        },
        {
            duration: 0,
            content: 'Damn it, why? Why did you...',
            startOfParagraph: null,
            startTime: '00:18:54.718',
            endTime: '00:18:56.553',
        },
        {
            duration: 0,
            content: 'Oh, Arthur, stop it.',
            startOfParagraph: null,
            startTime: '00:19:01.475',
            endTime: '00:19:02.976',
        },
        {
            duration: 0,
            content: 'Stop it.',
            startOfParagraph: null,
            startTime: '00:19:06.188',
            endTime: '00:19:08.357',
        },
        {
            duration: 0,
            content: 'Stop it.',
            startOfParagraph: null,
            startTime: '00:19:09.149',
            endTime: '00:19:10.234',
        },
        {
            duration: 0,
            content: 'Stop it. Stop it.',
            startOfParagraph: null,
            startTime: '00:19:12.236',
            endTime: '00:19:15.322',
        },
        {
            duration: 0,
            content: 'Stop it.',
            startOfParagraph: null,
            startTime: '00:19:16.782',
            endTime: '00:19:18.742',
        },
        {
            duration: 0,
            content: 'Stop it.',
            startOfParagraph: null,
            startTime: '00:19:18.825',
            endTime: '00:19:20.202',
        },
        {
            duration: 0,
            content: 'Stop it.',
            startOfParagraph: null,
            startTime: '00:19:22.120',
            endTime: '00:19:23.121',
        },
        {
            duration: 0,
            content: 'Stop it.',
            startOfParagraph: null,
            startTime: '00:19:23.205',
            endTime: '00:19:24.248',
        },
        {
            duration: 0,
            content: 'Stop it. Stop it.',
            startOfParagraph: null,
            startTime: '00:19:26.500',
            endTime: '00:19:28.544',
        },
        {
            duration: 0,
            content: 'Stop it.',
            startOfParagraph: null,
            startTime: '00:19:28.627',
            endTime: '00:19:29.670',
        },
        {
            duration: 0,
            content: 'Stop it.',
            startOfParagraph: null,
            startTime: '00:19:30.838',
            endTime: '00:19:31.839',
        },
        {
            duration: 0,
            content: 'Vision, help him.',
            startOfParagraph: null,
            startTime: '00:19:31.922',
            endTime: '00:19:32.965',
        },
        {
            duration: 0,
            content: 'Let me help you up.',
            startOfParagraph: null,
            startTime: '00:19:47.980',
            endTime: '00:19:48.981',
        },
        {
            duration: 0,
            content: 'Give me your hand.',
            startOfParagraph: null,
            startTime: '00:19:49.481',
            endTime: '00:19:50.482',
        },
        {
            duration: 0,
            content: 'All right, steady on, sir.',
            startOfParagraph: null,
            startTime: '00:19:52.234',
            endTime: '00:19:53.569',
        },
        {
            duration: 0,
            content: 'Well, would you look\nat the time?',
            startOfParagraph: null,
            startTime: '00:19:58.282',
            endTime: '00:20:01.243',
        },
        {
            duration: 0,
            content: "Yes. We'd better be going.",
            startOfParagraph: null,
            startTime: '00:20:01.368',
            endTime: '00:20:03.787',
        },
        {
            duration: 0,
            content: 'Well... Are you both all right?',
            startOfParagraph: null,
            startTime: '00:20:05.163',
            endTime: '00:20:07.165',
        },
        {
            duration: 0,
            content: 'We had such a lovely time.',
            startOfParagraph: null,
            startTime: '00:20:07.666',
            endTime: '00:20:10.335',
        },
        {
            duration: 0,
            content: 'This guest is leaving your home.',
            startOfParagraph: null,
            startTime: '00:20:11.253',
            endTime: '00:20:14.089',
        },
        {
            duration: 0,
            content: 'Yes, thank you for coming.',
            startOfParagraph: null,
            startTime: '00:20:15.757',
            endTime: '00:20:17.926',
        },
        {
            duration: 0,
            content: 'You made me proud tonight, son.',
            startOfParagraph: null,
            startTime: '00:20:20.095',
            endTime: '00:20:21.555',
        },
        {
            duration: 0,
            content:
                'First thing Monday morning,\nyou and me are gonna have a little chat.',
            startOfParagraph: null,
            startTime: '00:20:21.638',
            endTime: '00:20:24.433',
        },
        {
            duration: 0,
            content: "We'll see about that promotion.",
            startOfParagraph: null,
            startTime: '00:20:25.392',
            endTime: '00:20:27.644',
        },
        {
            duration: 0,
            content: 'Yes, sir! Thank you, sir!',
            startOfParagraph: null,
            startTime: '00:20:27.728',
            endTime: '00:20:28.896',
        },
        {
            duration: 0,
            content: 'Thank you.',
            startOfParagraph: null,
            startTime: '00:20:31.565',
            endTime: '00:20:32.566',
        },
        {
            duration: 0,
            content: 'Oh...',
            startOfParagraph: null,
            startTime: '00:20:36.195',
            endTime: '00:20:37.321',
        },
        {
            duration: 0,
            content: 'What a charming door knocker.',
            startOfParagraph: null,
            startTime: '00:20:38.780',
            endTime: '00:20:40.908',
        },
        {
            duration: 0,
            content: 'Good night!',
            startOfParagraph: null,
            startTime: '00:20:42.451',
            endTime: '00:20:43.452',
        },
        {
            duration: 0,
            content: 'We are an unusual couple, ya know?',
            startOfParagraph: null,
            startTime: '00:20:54.880',
            endTime: '00:20:56.965',
        },
        {
            duration: 0,
            content: "Oh, I don't think\nthat was ever in question.",
            startOfParagraph: null,
            startTime: '00:20:57.049',
            endTime: '00:20:58.926',
        },
        {
            duration: 0,
            content: "Well, what I mean is...\nWe don't have an anniversary.",
            startOfParagraph: null,
            startTime: '00:20:59.426',
            endTime: '00:21:03.764',
        },
        {
            duration: 0,
            content: '- Huh.\n- Or a song.',
            startOfParagraph: null,
            startTime: '00:21:03.847',
            endTime: '00:21:05.557',
        },
        {
            duration: 0,
            content: 'Or even wedding rings.',
            startOfParagraph: null,
            startTime: '00:21:06.225',
            endTime: '00:21:07.684',
        },
        {
            duration: 0,
            content: 'Well, we could remedy that.',
            startOfParagraph: null,
            startTime: '00:21:07.768',
            endTime: '00:21:09.144',
        },
        {
            duration: 0,
            content: 'Today could be our anniversary.',
            startOfParagraph: null,
            startTime: '00:21:09.811',
            endTime: '00:21:11.313',
        },
        {
            duration: 0,
            content: 'Of what? Surviving our first dinner party?',
            startOfParagraph: null,
            startTime: '00:21:11.396',
            endTime: '00:21:13.982',
        },
        {
            duration: 0,
            content: 'Precisely. And our song could be?',
            startOfParagraph: null,
            startTime: '00:21:14.066',
            endTime: '00:21:16.527',
        },
        {
            duration: 0,
            content: 'Yakety Yak, naturally.',
            startOfParagraph: null,
            startTime: '00:21:16.610',
            endTime: '00:21:17.903',
        },
        {
            duration: 0,
            content: '- Naturally.\n- Hmm.',
            startOfParagraph: null,
            startTime: '00:21:17.986',
            endTime: '00:21:18.987',
        },
        {
            duration: 0,
            content: 'And the rings?',
            startOfParagraph: null,
            startTime: '00:21:20.656',
            endTime: '00:21:21.657',
        },
        {
            duration: 0,
            content: "Well, couldn't you make some for us?",
            startOfParagraph: null,
            startTime: '00:21:23.033',
            endTime: '00:21:24.535',
        },
        {
            duration: 0,
            content: 'I do.',
            startOfParagraph: null,
            startTime: '00:21:32.709',
            endTime: '00:21:33.710',
        },
        {
            duration: 0,
            content: 'Do you?',
            startOfParagraph: null,
            startTime: '00:21:34.795',
            endTime: '00:21:35.796',
        },
        {
            duration: 0,
            content: 'Yes. I do.',
            startOfParagraph: null,
            startTime: '00:21:37.005',
            endTime: '00:21:39.216',
        },
        {
            duration: 0,
            content: 'And they lived happily ever after.',
            startOfParagraph: null,
            startTime: '00:21:41.009',
            endTime: '00:21:42.886',
        },
    ],
};
